.TH "Aluno" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Aluno \- 
.PP
\fBAluno\fP de uma escola\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Aluno\&.h>\fP
.PP
Inherits \fBPessoa\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAluno\fP (string n, int numero, \fBTurma\fP *t)"
.br
.ti -1c
.RI "int \fBgetNumero\fP ()"
.br
.ti -1c
.RI "\fBTurma\fP * \fBgetTurma\fP ()"
.br
.ti -1c
.RI "void \fBsetNumero\fP (int numero)"
.br
.ti -1c
.RI "void \fBsetTurma\fP (\fBTurma\fP *t)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBAluno\fP *a2)"
.br
.ti -1c
.RI "string \fBprint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAluno\fP de uma escola\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Aluno::Aluno (stringn, intnumero, \fBTurma\fP *t)"
\fBParameters:\fP
.RS 4
\fIn\fP 
.br
\fInumero\fP 
.br
\fIt\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Aluno::getNumero ()"
\fBReturns:\fP
.RS 4
int _numero 
.RE
.PP

.SS "\fBTurma\fP * Aluno::getTurma ()"
\fBReturns:\fP
.RS 4
\fBTurma\fP _turma 
.RE
.PP

.SS "bool Aluno::operator== (\fBAluno\fP *a2)"
\fBParameters:\fP
.RS 4
\fIa2\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "string Aluno::print ()\fC [virtual]\fP"
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBPessoa\fP\&.
.SS "void Aluno::setNumero (intnumero)"
\fBParameters:\fP
.RS 4
\fInumero\fP 
.RE
.PP

.SS "void Aluno::setTurma (\fBTurma\fP *t)"
\fBParameters:\fP
.RS 4
\fIt\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
