.TH "AlunoNaoExistente" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AlunoNaoExistente \- 
.PP
Excepcao lancada quando o \fBAluno\fP a ser acedido nao existe\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Excepcao\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAlunoNaoExistente\fP (\fBAluno\fP *a)"
.br
.ti -1c
.RI "string \fBgetErro\fP ()"
.br
.ti -1c
.RI "virtual \fB~AlunoNaoExistente\fP ()"
.br
.RI "\fIDestrutor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAluno\fP * \fBaluno\fP"
.br
.RI "\fI\fBAluno\fP inesxistente\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Excepcao lancada quando o \fBAluno\fP a ser acedido nao existe\&. 
.SH "Member Function Documentation"
.PP 
.SS "string AlunoNaoExistente::getErro ()\fC [inline]\fP"
< Mensagem de erro lancada pela excepcao 

.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
