.TH "DirectorTurma" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DirectorTurma \- 
.PP
Classe derivado de \fBProfessor\fP tendo a mais um vector com as turmas de que e responsavel\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Professor\&.h>\fP
.PP
Inherits \fBProfessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectorTurma\fP (string n, \fBDisciplina\fP *d, \fBTurma\fP *t, \fBTurma\fP *t_responsavel)"
.br
.ti -1c
.RI "bool \fBaddTurmaResponsavel\fP (\fBTurma\fP *t)"
.br
.ti -1c
.RI "bool \fBremoveTurmaResponsavel\fP (const int id)"
.br
.ti -1c
.RI "vector< \fBTurma\fP * > \fBgetTurmasResponsaveis\fP ()"
.br
.ti -1c
.RI "\fB~DirectorTurma\fP ()"
.br
.RI "\fIDestructor for \fBDirectorTurma\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Classe derivado de \fBProfessor\fP tendo a mais um vector com as turmas de que e responsavel\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DirectorTurma::DirectorTurma (stringn, \fBDisciplina\fP *d, \fBTurma\fP *t, \fBTurma\fP *t_responsavel)"
\fBParameters:\fP
.RS 4
\fIn\fP 
.br
\fId\fP 
.br
\fIt\fP 
.br
\fIt_responsavel\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool DirectorTurma::addTurmaResponsavel (\fBTurma\fP *t)"
\fBParameters:\fP
.RS 4
\fIt\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool DirectorTurma::removeTurmaResponsavel (const intid)"
\fBParameters:\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
