.TH "Disciplina" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Disciplina \- 
.PP
Class representa uma \fBDisciplina\fP contendo a sua designacao, duracao e hora de inicio\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Disciplina\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisciplina\fP (string _nome, int d, int h)"
.br
.ti -1c
.RI "string \fBgetNome\fP () const "
.br
.ti -1c
.RI "void \fBsetNome\fP (string _nome)"
.br
.ti -1c
.RI "int \fBgetDuracao\fP () const "
.br
.ti -1c
.RI "void \fBsetDuracao\fP (int d)"
.br
.ti -1c
.RI "int \fBgetHoraInicio\fP () const "
.br
.ti -1c
.RI "void \fBsetHoraInicio\fP (int h)"
.br
.ti -1c
.RI "int \fBgetHoraFim\fP () const "
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBDisciplina\fP *d2)"
.br
.RI "\fIVerificasse quando o nome entre os dois objetos e igual\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Class representa uma \fBDisciplina\fP contendo a sua designacao, duracao e hora de inicio\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Disciplina::Disciplina (stringnome, intd, inth)"
\fBParameters:\fP
.RS 4
\fInome\fP 
.br
\fId\fP 
.br
\fIh\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Disciplina::getDuracao () const"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "int Disciplina::getHoraFim () const"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "int Disciplina::getHoraInicio () const"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "string Disciplina::getNome () const"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Disciplina::operator== (\fBDisciplina\fP *d2)"

.PP
Verificasse quando o nome entre os dois objetos e igual\&. \fBParameters:\fP
.RS 4
\fId2\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void Disciplina::setDuracao (intd)"
\fBParameters:\fP
.RS 4
\fId\fP 
.RE
.PP

.SS "void Disciplina::setHoraInicio (inth)"
\fBParameters:\fP
.RS 4
\fIh\fP 
.RE
.PP

.SS "void Disciplina::setNome (stringnome)"
\fBParameters:\fP
.RS 4
\fInome\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
