.TH "Escola" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Escola \- 
.PP
Representa uma \fBEscola\fP contendo todos os seus Alunos, Professores, Turmas, Disciplinas e Horarios\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Escola\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "vector< \fBAluno\fP * > \fBgetAlunos\fP ()"
.br
.ti -1c
.RI "void \fBsetAluno\fP (\fBAluno\fP *a)"
.br
.RI "\fIAcrescenta alunos ao vector _alunos\&. \fP"
.ti -1c
.RI "\fBAluno\fP * \fBgetAlunoByNome\fP (string n)"
.br
.RI "\fIDevolve o \fBAluno\fP com o nome igual a n\&. \fP"
.ti -1c
.RI "bool \fBaddAluno\fP (string nome, int numero, \fBTurma\fP *t)"
.br
.RI "\fIAdiciona um \fBAluno\fP a \fBEscola\fP\&. \fP"
.ti -1c
.RI "string \fBshowAluno\fP (\fBAluno\fP *a)"
.br
.RI "\fIMostra o \fBAluno\fP no ecra\&. \fP"
.ti -1c
.RI "bool \fBupdateAluno\fP (\fBAluno\fP *a)"
.br
.RI "\fIAltera informacao do \fBAluno\fP\&. \fP"
.ti -1c
.RI "bool \fBremoveAluno\fP (\fBAluno\fP *a)"
.br
.RI "\fIRemove um \fBAluno\fP da \fBEscola\fP\&. \fP"
.ti -1c
.RI "vector< \fBProfessor\fP * > \fBgetProfessores\fP ()"
.br
.RI "\fIDevolve todos os professores existentes na \fBEscola\fP\&. \fP"
.ti -1c
.RI "void \fBsetProfessor\fP (\fBProfessor\fP *p)"
.br
.RI "\fIAcrescenta professores ao vector _professores\&. \fP"
.ti -1c
.RI "\fBProfessor\fP * \fBgetProfessorByNome\fP (const string n)"
.br
.RI "\fIDevolve o \fBProfessor\fP com o nome igual a n\&. \fP"
.ti -1c
.RI "bool \fBaddProfessor\fP (string n, string d, int t)"
.br
.RI "\fIAdiciona um \fBProfessor\fP a \fBEscola\fP\&. \fP"
.ti -1c
.RI "string \fBshowProfessor\fP (\fBProfessor\fP *p)"
.br
.RI "\fIMostra o \fBProfessor\fP no ecra\&. \fP"
.ti -1c
.RI "bool \fBupdateProfessor\fP (\fBProfessor\fP *p)"
.br
.RI "\fIAltera a informacao do \fBProfessor\fP\&. \fP"
.ti -1c
.RI "bool \fBremoveProfessor\fP (const string n)"
.br
.RI "\fIRemove um \fBProfessor\fP da \fBEscola\fP\&. \fP"
.ti -1c
.RI "vector< \fBTurma\fP * > \fBgetTurmas\fP ()"
.br
.RI "\fIDevolve todas as turmas existentes na \fBEscola\fP\&. \fP"
.ti -1c
.RI "void \fBsetTurma\fP (\fBTurma\fP *t)"
.br
.RI "\fIAcrescenta turmas ao vector turmas\&. \fP"
.ti -1c
.RI "\fBTurma\fP * \fBgetTurmaById\fP (int id)"
.br
.RI "\fIDevolve a \fBTurma\fP com o id igual a id\&. \fP"
.ti -1c
.RI "bool \fBaddTurma\fP (int id, int anoEscolar)"
.br
.RI "\fIAdiciona uma \fBTurma\fP a \fBEscola\fP\&. \fP"
.ti -1c
.RI "string \fBshowTurma\fP (\fBTurma\fP *t)"
.br
.RI "\fIMostra a \fBTurma\fP no ecra\&. \fP"
.ti -1c
.RI "bool \fBupdateTurma\fP (\fBTurma\fP *t)"
.br
.RI "\fIAltera a informacao da \fBTurma\fP\&. \fP"
.ti -1c
.RI "bool \fBremoveTurma\fP (const int id)"
.br
.RI "\fIRemove uma \fBTurma\fP da \fBEscola\fP\&. \fP"
.ti -1c
.RI "vector< \fBDisciplina\fP * > \fBgetDiscipinas\fP ()"
.br
.RI "\fIDevolve todas as Disciplinas que sao leccionadas na \fBEscola\fP\&. \fP"
.ti -1c
.RI "void \fBsetDisciplina\fP (\fBDisciplina\fP *d)"
.br
.RI "\fIAcrescenta disciplinas ao vector _disciplinas\&. \fP"
.ti -1c
.RI "\fBDisciplina\fP * \fBgetDisciplinaByNome\fP (const string n)"
.br
.RI "\fIDevolve a \fBDisciplina\fP com o nome igual a n\&. \fP"
.ti -1c
.RI "bool \fBaddDisciplina\fP (string nome, int d, int h)"
.br
.RI "\fIAdiciona uma \fBDisciplina\fP a \fBEscola\fP\&. \fP"
.ti -1c
.RI "string \fBshowDisciplina\fP (\fBDisciplina\fP *d)"
.br
.RI "\fIMostra a \fBDisciplina\fP no ecra\&. \fP"
.ti -1c
.RI "bool \fBupdateDisciplina\fP (\fBDisciplina\fP *d)"
.br
.RI "\fIAltera a informacao da \fBDisciplina\fP\&. \fP"
.ti -1c
.RI "bool \fBremoveDisciplina\fP (const string n)"
.br
.RI "\fIRemove uma disciplina da \fBEscola\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Representa uma \fBEscola\fP contendo todos os seus Alunos, Professores, Turmas, Disciplinas e Horarios\&. 
.SH "Member Function Documentation"
.PP 
.SS "bool Escola::addAluno (stringnome, intnumero, \fBTurma\fP *t)"

.PP
Adiciona um \fBAluno\fP a \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fInome\fP 
.br
\fInumero\fP 
.br
\fIt\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::addDisciplina (stringnome, intd, inth)"

.PP
Adiciona uma \fBDisciplina\fP a \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fInome\fP 
.br
\fId\fP 
.br
\fIh\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::addProfessor (stringn, stringd, intt)"

.PP
Adiciona um \fBProfessor\fP a \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fIn\fP 
.br
\fId\fP 
.br
\fIt\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::addTurma (intid, intanoEscolar)"

.PP
Adiciona uma \fBTurma\fP a \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fIid\fP 
.br
\fIanoEscolar\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "\fBAluno\fP * Escola::getAlunoByNome (stringn)"

.PP
Devolve o \fBAluno\fP com o nome igual a n\&. \fBParameters:\fP
.RS 4
\fIn\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "vector< \fBAluno\fP * > Escola::getAlunos ()"
\fBReturns:\fP
.RS 4
int _alunos 
.RE
.PP

.SS "vector< \fBDisciplina\fP * > Escola::getDiscipinas ()"

.PP
Devolve todas as Disciplinas que sao leccionadas na \fBEscola\fP\&. \fBReturns:\fP
.RS 4
Disiciplina _disciplinas 
.RE
.PP

.SS "\fBDisciplina\fP * Escola::getDisciplinaByNome (const stringn)"

.PP
Devolve a \fBDisciplina\fP com o nome igual a n\&. \fBParameters:\fP
.RS 4
\fIn\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "\fBProfessor\fP * Escola::getProfessorByNome (const stringn)"

.PP
Devolve o \fBProfessor\fP com o nome igual a n\&. \fBParameters:\fP
.RS 4
\fIn\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "vector< \fBProfessor\fP * > Escola::getProfessores ()"

.PP
Devolve todos os professores existentes na \fBEscola\fP\&. \fBReturns:\fP
.RS 4
\fBProfessor\fP * _professores 
.RE
.PP

.SS "\fBTurma\fP * Escola::getTurmaById (intid)"

.PP
Devolve a \fBTurma\fP com o id igual a id\&. \fBParameters:\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "vector< \fBTurma\fP * > Escola::getTurmas ()"

.PP
Devolve todas as turmas existentes na \fBEscola\fP\&. \fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::removeAluno (\fBAluno\fP *a)"

.PP
Remove um \fBAluno\fP da \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fIa\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.SS "bool Escola::removeDisciplina (const stringn)"

.PP
Remove uma disciplina da \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fIn\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::removeProfessor (const stringn)"

.PP
Remove um \fBProfessor\fP da \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fIn\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::removeTurma (const intid)"

.PP
Remove uma \fBTurma\fP da \fBEscola\fP\&. \fBParameters:\fP
.RS 4
\fIid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void Escola::setDisciplina (\fBDisciplina\fP *d)"

.PP
Acrescenta disciplinas ao vector _disciplinas\&. \fBParameters:\fP
.RS 4
\fId\fP 
.RE
.PP

.SS "void Escola::setProfessor (\fBProfessor\fP *p)"

.PP
Acrescenta professores ao vector _professores\&. Set method Professor* into Professores array\&.
.PP
\fBParameters:\fP
.RS 4
\fIp\fP 
.RE
.PP

.SS "void Escola::setTurma (\fBTurma\fP *t)"

.PP
Acrescenta turmas ao vector turmas\&. \fBParameters:\fP
.RS 4
\fIt\fP 
.RE
.PP

.SS "string Escola::showAluno (\fBAluno\fP *a)"

.PP
Mostra o \fBAluno\fP no ecra\&. \fBParameters:\fP
.RS 4
\fIa\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "string Escola::showDisciplina (\fBDisciplina\fP *d)"

.PP
Mostra a \fBDisciplina\fP no ecra\&. \fBParameters:\fP
.RS 4
\fId\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "string Escola::showProfessor (\fBProfessor\fP *p)"

.PP
Mostra o \fBProfessor\fP no ecra\&. \fBParameters:\fP
.RS 4
\fIp\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "string Escola::showTurma (\fBTurma\fP *t)"

.PP
Mostra a \fBTurma\fP no ecra\&. \fBParameters:\fP
.RS 4
\fIt\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::updateAluno (\fBAluno\fP *a)"

.PP
Altera informacao do \fBAluno\fP\&. \fBParameters:\fP
.RS 4
\fIa\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::updateDisciplina (\fBDisciplina\fP *d)"

.PP
Altera a informacao da \fBDisciplina\fP\&. \fBParameters:\fP
.RS 4
\fId\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::updateProfessor (\fBProfessor\fP *p)"

.PP
Altera a informacao do \fBProfessor\fP\&. \fBParameters:\fP
.RS 4
\fIp\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Escola::updateTurma (\fBTurma\fP *t)"

.PP
Altera a informacao da \fBTurma\fP\&. \fBParameters:\fP
.RS 4
\fIt\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
