.TH "Horario" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Horario \- 
.PP
Horário de uma \fBTurma\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Horario\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "vector< \fBDisciplina\fP * > \fBgetDisciplinas\fP () const "
.br
.ti -1c
.RI "bool \fBaddDisciplina\fP (\fBDisciplina\fP *d)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Horário de uma \fBTurma\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
