.TH "Pessoa" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pessoa \- 
.PP
Classe Base para \fBProfessor\fP e \fBAluno\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Professor\&.h>\fP
.PP
Inherited by \fBAluno\fP, and \fBProfessor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPessoa\fP (string n)"
.br
.ti -1c
.RI "void \fBsetNome\fP (const string n)"
.br
.ti -1c
.RI "string \fBgetNome\fP () const "
.br
.ti -1c
.RI "virtual string \fBprint\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classe Base para \fBProfessor\fP e \fBAluno\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
