.TH "ProfessorNaoExistente" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProfessorNaoExistente \- 
.PP
Excepcao lancada quando o \fBProfessor\fP a ser acedido nao existe\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Excepcao\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProfessorNaoExistente\fP (\fBProfessor\fP *p)"
.br
.ti -1c
.RI "string \fBgetErro\fP ()"
.br
.ti -1c
.RI "virtual \fB~ProfessorNaoExistente\fP ()"
.br
.RI "\fIDestrutor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBProfessor\fP * \fBprofessor\fP"
.br
.RI "\fI\fBAluno\fP inesxistente\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Excepcao lancada quando o \fBProfessor\fP a ser acedido nao existe\&. 
.SH "Member Function Documentation"
.PP 
.SS "string ProfessorNaoExistente::getErro ()\fC [inline]\fP"
< Mensagem de erro lancada pela excepcao 

.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
