.TH "Turma" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Turma \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTurma\fP ()"
.br
.RI "\fIdefault empty constructor for \fBTurma\fP \fP"
.ti -1c
.RI "\fBTurma\fP (int id, int anoEscolar)"
.br
.RI "\fIConstructor non-empty for \fBTurma\fP\&. \fP"
.ti -1c
.RI "\fBTurma\fP (int id)"
.br
.ti -1c
.RI "virtual \fB~Turma\fP ()"
.br
.RI "\fIDefault destructor\&. \fP"
.ti -1c
.RI "int \fBgetID\fP ()"
.br
.ti -1c
.RI "int \fBgetAnoEscolar\fP ()"
.br
.ti -1c
.RI "\fBHorario\fP * \fBgetHorario\fP ()"
.br
.ti -1c
.RI "void \fBsetID\fP (int i)"
.br
.ti -1c
.RI "void \fBsetAnoEscolar\fP (int ae)"
.br
.ti -1c
.RI "void \fBsetHorario\fP (\fBHorario\fP *h)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (\fBTurma\fP *t2)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Turma::Turma (intid, intanoEscolar)"

.PP
Constructor non-empty for \fBTurma\fP\&. \fBParameters:\fP
.RS 4
\fIid\fP 
.br
\fIanoEscolar\fP 
.RE
.PP

.SS "Turma::Turma (intid)"
\fBParameters:\fP
.RS 4
\fIid\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "int Turma::getAnoEscolar ()"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "\fBHorario\fP * Turma::getHorario ()"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "int Turma::getID ()"
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "bool Turma::operator== (\fBTurma\fP *t2)"
\fBParameters:\fP
.RS 4
\fIt2\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void Turma::setAnoEscolar (intae)"
\fBParameters:\fP
.RS 4
\fIae\fP 
.RE
.PP

.SS "void Turma::setHorario (\fBHorario\fP *h)"
\fBParameters:\fP
.RS 4
\fIh\fP 
.RE
.PP

.SS "void Turma::setID (inti)"
\fBParameters:\fP
.RS 4
\fIi\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
