.TH "TurmaNaoExistente" 3 "Mon Nov 11 2013" "AEDA TP1 2013/2014" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TurmaNaoExistente \- 
.PP
Excepcao lancada quando a \fBTurma\fP a ser acedida nao existe\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Excepcao\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTurmaNaoExistente\fP (\fBTurma\fP *t)"
.br
.ti -1c
.RI "string \fBgetErro\fP ()"
.br
.RI "\fIMensagem de erro lancada pela excepcao\&. \fP"
.ti -1c
.RI "virtual \fB~TurmaNaoExistente\fP ()"
.br
.RI "\fIDestrutor\&. \fP"
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTurma\fP * \fBturma\fP"
.br
.RI "\fI\fBTurma\fP inesxistente\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Excepcao lancada quando a \fBTurma\fP a ser acedida nao existe\&. 
.SH "Member Function Documentation"
.PP 
.SS "string TurmaNaoExistente::getErro ()\fC [inline]\fP"

.PP
Mensagem de erro lancada pela excepcao\&. \fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for AEDA TP1 2013/2014 from the source code\&.
